const TODO_SEARCHED = "TODO_SEARCHED";
const TODO_CLEAR = "TODO_CLEAR";
const TODO_ADDED = "TODO_ADDED";
const DESCRIPTION_CHANGED = "DESCRIPTION_CHANGED";
const TODO_MARKED_AS_DONE = "TODO_MARKED_AS_DONE";
const TODO_MARKED_AS_PENDING = "TODO_MARKED_AS_PENDING";
const ACTIONS = {
  TODO_SEARCHED,
  TODO_CLEAR,
  TODO_ADDED,
  DESCRIPTION_CHANGED,
  TODO_MARKED_AS_DONE,
  TODO_MARKED_AS_PENDING
};

export default ACTIONS;
